### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Kreyren** [Kreyren/Gitpod-OpenShift#1]
Gitpod <https://gitpod.io/> is theia-based online IDE <https://github.com/eclipse-theia/theia> with GNU/Linux terminal available on any github repository with url prefix `https://gitpod.io/#<GitHub_URL_HERE>` i.e https://gitpod.io/#https://github.com/Kreyren/Gitpod-OpenShift/issues/1 (requires github account)

---

### Ideal solution
- Everything (excluding the registration) done from a CLI or a method that can be done by the end-user painlessly to deploy gitpod within a short amount of time with the option to customize the result of the runtime.

## Checklist

- [ ] Deploy gitpod on OpenShift from a terminal using any shell on any OS ideally without the need for root account on local system.

    We need to login in `oc` command for which we nee `OpenShift Container Platform server URL` based on https://docs.openshift.com/container-platform/4.4/cli_reference/openshift_cli/getting-started-cli.html#cli-logging-in_cli-developer-commands

  - [ ] Have access to the cluster? -> How to get the `OpenShift Container Platform server URL` ?
  - [ ] Login
  - [ ] Create a cluster

### Checklist - Unable to create the cluster from CLI
This is an alternative checklist in case we can't create the `OpenShift Container Platform server` to get it's URL required for `oc login`

Update: seems that we can make the cluster using `openshift-installer` for us to then login using `oc login`

- [ ] Deploy gitpod on OpenShift from a terminal using any shell on any OS ideally without the need for root account on local system.
  - [ ] Go on https://cloud.redhat.com/openshift/install/openstack/installer-provisioned and get the installer
  - [ ] Pull secrets (required during the setup)
  - [ ] Extract the installer
  - [ ] Configure the `clouds.yaml` (?)
  - [ ] Run the installer

### Relevants
- https://access.redhat.com/support/cases/#/case/02661231
